version: '2'
services:
    jenkins.docker:
        image: Magicfirm/jenkins-blueocean
        ports:
            - "8081:8080"
            - "50000:50000"
        volumes:
            - ./jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        group_add:
            - docker
